version: '3.8'
services:
  model_server:
    build:
      dockerfile: ./servers/model_server/Dockerfile
    image: model_server
    ports:
      - '8000:8000'
  frontend_server:
    build:
      dockerfile: ./servers/frontend_server/Dockerfile
    image: frontend_server
    ports:
      - '80:8501'
    environment:
      - MODEL_SERVER_URL=http://model_server:8000
